url: https://uncpmclub.com
baseurl: 



# Site settings
title: UNC Product Management Club
email: your-email@domain.com
description: "UNC PM Club aims to introduce product management disciplines to more undergraduate students. We connect students who are passionate about product and empower them to develop not only technical knowledge, but also that of the business and design-side of the world through a series of workshops, invited talks, and product sprints."


# Team names, titles and social links
people:
- name: Yujie Tao
  pic: 1
  position: Operations
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/yujie-tao/

- name: Kushagra Chopra
  pic: 2
  position: Events
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/kushagra-chopra16/

- name: Sunny Deshwal
  pic: 3
  position: External Relations 
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/sunnydeshwal/

- name: Katherine Wilkins
  pic: 4
  position: Marketing 
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/katherine-wilkins-3b7b73190/

- name: Angie Shen
  pic: 5
  position: Graphic Design
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/mingxuan-shen-abb49b171/

- name: Jojo Yang
  pic: 3
  position: Graphic Design
  social:
    - title: linkedin
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/unc-product-management-club/
  - title: facebook
    url: https://www.facebook.com/UNCProductManagementClub/
  - title: github
    url: https://github.com/unc-pmclub


# Postal address (add as many lines as necessary)

# Build settings
markdown: kramdown
permalink: pretty